// <auto-generated />
namespace BugTracker.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class initial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial));
        
        string IMigrationMetadata.Id
        {
<<<<<<< HEAD:BugTracker.Data/Migrations/202109201523283_initial.Designer.cs
            get { return "202109201523283_initial"; }
=======
            get { return "202109201514224_initial"; }
>>>>>>> 4c13a46f11181a4f59c4deec7b7a56fda9e798e9:BugTracker.Data/Migrations/202109201514224_initial.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
